---
- name: Copy Config files
  copy: 
    src: "../nginx"
    dest: /src/compose

- name: Install wordpress
  docker_service:
    project_src: /src/
    files: 
      - compose/docker-compose.yml
      - compose/docker-compose-nginx.yml
    build: yes
    restarted: true    
    state: present
  register: output

- debug:
    var: output