---
- name: Create an ec2 instance 
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type}}"
    image: "{{ ami }}"
    wait: true
    region: "{{ aws_region }}"
    count_tag:
      Name: "{{ item }}"
    instance_tags:
      Name: "{{ item }}"
    vpc_subnet_id:    "{{ public_subnet_id }}"
    assign_public_ip: yes
    instance_profile_name: "role-{{ vpc_name }}-ecs"
  register: ec2

  with_items: 
    - prom
    - wordpress