version: '3'
services:
  wordpress:
    image: wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    links:
      - db:mysql
    ports:
      - 8080:80
    restart: always

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: always
    
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    restart: always

  mysql-exporter:
    image: prom/mysqld-exporter
    ports:
      - 9104:9104
    environment:
      - DATA_SOURCE_NAME="root:{{ .Values.mariadbRootPassword }}@(localhost:3306)/"
    restart: always
  
  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    restart: always
    volumes:
      - ./monitoring_config/blackbox-exporter:/etc/blackbox_exporter

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8088:8080
    restart: always

  nginx-exporter:
    image: fish/nginx-exporter
    command:
      - "-nginx.scrape_uri=http://127.0.0.1:8080/nginx_status"
    ports: 
      - 9113:9113
