version: '3'

networks: 
  internal:

services:
  wp:
    image: wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    restart: always
    networks: 
      - internal

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: always
    networks: 
      - internal

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    restart: always

  mysql-exporter:
    image: prom/mysqld-exporter
    ports:
      - 9104:9104
    environment:
      - DATA_SOURCE_NAME="root:{{ .Values.mariadbRootPassword }}@(db:3306)/"
    restart: always
    networks: 
      - internal

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    restart: always
    volumes:
      - ../monitoring_config/blackbox-exporter:/etc/blackbox_exporter

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8088:8080
    restart: always
    
  ecs-exporter: 
    image: slok/ecs-exporter
    command:
      - "-aws.region=eu-west-1"
      - "-debug"
    ports: 
      - 9222:9222
    
  nginx: 
    image: nginx:latest
    restart: always
    volumes:
      - "../nginx:/etc/nginx/conf.d"
    ports:
      - 80:80
    networks: 
      - internal
    depends_on: 
      - wp

  nginx-exporter:
    image: fish/nginx-exporter
    ports: 
      - 9113:9113
    depends_on:
      - nginx
    command:
      - "-nginx.scrape_uri=http://nginx/nginx_status"
    networks: 
      - internal